name: HarpoJo
favicon: null
layout_spectrum: 0.9999637582805008
typography_spectrum: 0.4248026730492711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.22851166501641273
  lightness: 0.9784735087305307
  saturation: 0.8742233866360039
  rhythmicContrast: 0.48828092659823596
purpose: []
